name: Auto Deployment to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Build Site
      working-directory: ./BlazorPortfolioSite
      run: dotnet publish --configuration Release --output build

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v3
    - name: Upload Built Site as Pages Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: BlazorPortfolioSite/build/wwwroot

  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    runs-on: ubuntu-latest

    needs: build
    
    steps:
      - name: Deploy Pages Artifact to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2