name: gh-pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Publish
      working-directory: ./BlazorPortfolioSite
      run: dotnet publish --configuration Release --output build

    # Changes the base-tag in index.html from '/' to 'Blazor-Portfolio-Site' to match GitHub Pages repository subdirectory
    - name: Adjusting for MS Blazor Quirks pt. 1
      run: sed -i 's/<base href="\/" \/>/<base href="\/Blazor-Portfolio-Site\/" \/>/g' BlazorPortfolioSite/build/wwwroot/index.html

    # Add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Adjusting for MS Blazor Quirks pt. 2
      run: touch BlazorPortfolioSite/build/wwwroot/.nojekyll

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1